name: Bigeculty
description: Special Impossible Difficulty for Bige by FilipeeX
version: 420.69
main: filipeex.bigeculty.Bigeculty
author: FilipeeX

commands:
  bigeculty:
    usage: /<command>
    description: Main Command of Bigeculty Plugin
    aliases: [b, bc, bd, bg, bgculty, bculty, bgdiffimpossible, bgdiff]